package com.oneway.tools.redirector.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePartylist<M extends BasePartylist<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTitle(java.lang.String partyName) {
		set("title", partyName);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setDate(java.lang.String partyDate) {
		set("date", partyDate);
		return (M)this;
	}

	public java.lang.String getDate() {
		return getStr("date");
	}

	public M setPay(java.lang.String pay) {
		set("pay", pay);
		return (M)this;
	}

	public java.lang.String getPay() {
		return getStr("pay");
	}

	public M setApplied(java.lang.Integer applied) {
		set("applied", applied);
		return (M)this;
	}

	public java.lang.Integer getApplied() {
		return getInt("applied");
	}

	public M setLimit(java.lang.Integer limit) {
		set("limit", limit);
		return (M)this;
	}

	public java.lang.Integer getLimit() {
		return getInt("limit");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setImageUrl(java.lang.String imageUrl) {
		set("imageUrl", imageUrl);
		return (M)this;
	}

	public java.lang.String getImageUrl() {
		return getStr("imageUrl");
	}

	public M setDetail(java.lang.String detail) {
		set("detail", detail);
		return (M)this;
	}

	public java.lang.String getDetail() {
		return getStr("detail");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

}
