package com.oneway.tools.redirector.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseApplyinfo<M extends BaseApplyinfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setPartyId(java.lang.Integer partyId) {
		set("partyId", partyId);
		return (M)this;
	}

	public java.lang.Integer getPartyId() {
		return getInt("partyId");
	}

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setFormId(java.lang.String formId) {
		set("formId", formId);
		return (M)this;
	}

	public java.lang.String getFormId() {
		return getStr("formId");
	}

	public M setArrived(java.lang.Integer  arrived) {
		set("arrived", arrived);
		return (M)this;
	}

	public java.lang.Integer getArrived() {
		return getInt("arrived");
	}

	public M setConfirm(java.lang.Integer  confirm) {
		set("confirm", confirm);
		return (M)this;
	}

	public java.lang.Integer getConfirm() {
		return getInt("confirm");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
