package com.oneway.tools.redirector.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserlist<M extends BaseUserlist<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setNickName(java.lang.String nickName) {
		set("nickName", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return getStr("nickName");
	}

	public M setGender(java.lang.Integer gender) {
		set("gender", gender);
		return (M)this;
	}

	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}

	public java.lang.String getCountry() {
		return getStr("country");
	}

	public M setOpenId(java.lang.String openId) {
		set("openId", openId);
		return (M)this;
	}

	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setLanguage(java.lang.String language) {
		set("language", language);
		return (M)this;
	}

	public java.lang.String getLanguage() {
		return getStr("language");
	}

	public M setAvatarUrl(java.lang.String avatarUrl) {
		set("avatarUrl", avatarUrl);
		return (M)this;
	}

	public java.lang.String getAvatarUrl() {
		return getStr("avatarUrl");
	}

}
