package com.oneway.tools.redirector.model;

import com.oneway.tools.redirector.model.base.BaseApplyinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Applyinfo extends BaseApplyinfo<Applyinfo> {
	public static final Applyinfo dao = new Applyinfo().dao();
}
