package com.oneway.tools.redirector.model;

import com.oneway.tools.redirector.model.base.BasePartylist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Partylist extends BasePartylist<Partylist> {
	public static final Partylist dao = new Partylist().dao();
}
