package com.oneway.tools.redirector.model;

import com.oneway.tools.redirector.model.base.BaseReport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Report extends BaseReport<Report> {
	public static final Report dao = new Report().dao();
}
