package com.oneway.tools.redirector.model;

import com.oneway.tools.redirector.model.base.BaseUserlist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userlist extends BaseUserlist<Userlist> {
	public static final Userlist dao = new Userlist().dao();
}
